[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/profile"
  to = "/user/:id"
  status = 301
  query = {id = ":id"}

[[redirects]]
  from = "http://example.com/*"
  to = "https://www.example.com/:splat"
  status = 301
  force = true
